import { useState } from 'react';
import { Activity, BadgeCheck, BellRing, BrainCircuit, CheckCircle2, Download, FileClock, Filter, Network, Plus, Search, Server, Settings, ShieldCheck, Sparkles, UserCog, Users } from 'lucide-react';
import { AppShell } from '../components/AppShell';
import { TrendChart, ZoneBarChart } from '../components/Charts';
import { integrations, smartDomains } from '../data/mock';
import { Panel, SourceFooter, StatusBadge } from '../components/ui';

export function SmartCityPage() {
    return <AppShell subtitle="Pemantauan pelaksanaan inisiatif pintar mengikut MS ISO 37122:2019" title="Smart City · Bandar Pintar Klang 2035"><div className="flex flex-col gap-4">
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-[1.1fr_1.1fr_.8fr_.8fr]">
            <div className="panel flex items-center gap-4 p-4"><div className="flex size-20 items-center justify-center rounded-full border-[7px] border-cyan-400 text-xl font-bold text-white">75%</div><div><p className="text-xs font-semibold text-slate-200">Kemajuan keseluruhan</p><p className="mt-2 text-lg font-bold text-white">80<span className="text-slate-600">/107</span></p><p className="mt-1 text-[9px] text-emerald-400">8 domain aktif</p></div></div>
            <div className="panel p-4"><div className="flex items-center justify-between"><p className="text-[10px] text-slate-500">Skor pematuhan standard</p><BadgeCheck className="text-emerald-400" size={18} /></div><p className="mt-3 text-2xl font-bold text-emerald-400">78.4%</p><div className="mt-3 h-1.5 rounded-full bg-slate-800"><div className="h-1.5 w-[78%] rounded-full bg-emerald-400" /></div><p className="mt-2 text-[9px] text-slate-600">Indeks MS ISO 37122:2019</p></div>
            <div className="panel p-4"><p className="text-[10px] text-slate-500">Jumlah domain</p><p className="mt-3 text-2xl font-bold text-white">7</p><p className="mt-2 text-[9px] text-cyan-400">1 domain lengkap</p></div>
            <div className="panel p-4"><p className="text-[10px] text-slate-500">Sasaran</p><p className="mt-3 text-2xl font-bold text-amber-300">2035</p><p className="mt-2 text-[9px] text-slate-600">27 projek aktif</p></div>
        </div>
        <Panel action={<StatusBadge tone="info">7 domain</StatusBadge>} eyebrow="MS ISO 37122:2019" title="Domain Bandar Pintar"><div className="grid gap-3 p-3 sm:grid-cols-2 xl:grid-cols-4">{smartDomains.map((domain) => <button className="rounded-lg border border-slate-700 bg-slate-950/30 p-4 text-left hover:border-cyan-500/40" key={domain.name} type="button"><div className="flex items-center justify-between"><Sparkles size={15} style={{ color: domain.color }} /><span className="text-[10px] font-semibold" style={{ color: domain.color }}>{domain.value}%</span></div><p className="mt-3 text-xs font-semibold text-slate-200">{domain.name}</p><p className="mt-1 text-[9px] text-slate-500">{domain.count} inisiatif</p><div className="mt-3 h-1.5 rounded-full bg-slate-800"><div className="h-1.5 rounded-full" style={{ backgroundColor: domain.color, width: `${domain.value}%` }} /></div></button>)}</div><SourceFooter source="Rekod inisiatif Klang 2035" /></Panel>
        <div className="grid gap-4 xl:grid-cols-2"><Panel eyebrow="Pelaksanaan" title="Selesai vs dirancang mengikut domain"><div className="p-2"><ZoneBarChart /></div></Panel><Panel eyebrow="Prestasi" title="Kemajuan setiap fasa"><div className="p-2"><TrendChart /></div></Panel></div>
        <Panel action={<button className="flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-[10px] font-semibold text-slate-300" type="button"><Download size={13} />Ringkasan eksekutif</button>} eyebrow="Inisiatif utama" title="Pelaksanaan mengikut fasa"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-[10px]"><thead className="border-b border-slate-700 text-slate-500"><tr>{['Inisiatif', 'Domain', 'Fasa', 'Pemilik', 'Kemajuan', 'Status'].map((head) => <th className="px-4 py-3" key={head}>{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-700/50">{[['Pusat Kawalan Bandar Pintar', 'Government', 'Fasa 1', 'JTM', '92%', 'Dalam pelaksanaan'], ['Lampu Jalan Pintar', 'Infrastructure', 'Fasa 2', 'Kejuruteraan', '68%', 'Dalam pelaksanaan'], ['Sensor Kualiti Udara', 'Environment', 'Fasa 2', 'Persekitaran', '54%', 'Dirancang'], ['Mobiliti Hijau Klang', 'Mobility', 'Fasa 3', 'Perancang Bandar', '31%', 'Dirancang']].map((row) => <tr key={row[0]}>{row.map((cell, index) => <td className={`px-4 py-3 ${index === 0 ? 'font-semibold text-slate-200' : 'text-slate-400'}`} key={`${row[0]}-${index}`}>{cell}</td>)}</tr>)}</tbody></table></div></Panel>
    </div></AppShell>;
}

const aiCapabilities = [
    ['Pagar Maya (ROI)', 'Pencerobohan sempadan maya', '18 ROI aktif', 'normal'],
    ['Parkir Haram', 'Kenderaan di kawasan larangan', '6 zon aktif', 'warning'],
    ['ANPR', 'Pengecaman nombor plat', '97.2% ketepatan', 'normal'],
    ['Penjejakan Individu', 'Jejakan anonim merentas kamera', 'Mod demo sahaja', 'info'],
    ['Pengesanan Insiden', 'Pergaduhan, pergerakan pantas, jatuh', '3 model aktif', 'normal'],
    ['Objek Ditinggalkan', 'Objek statik melebihi ambang', '8 kamera', 'normal'],
    ['Pengiraan Kenderaan', 'Kiraan aliran mengikut zon', '12 laluan', 'normal'],
    ['Pengiraan Individu', 'Kiraan kapasiti kawasan', '5 zon', 'normal'],
] as const;

export function AiAnalyticsPage() {
    return <AppShell subtitle="Katalog keupayaan analitik video dan konfigurasi ROI" title="Fungsi Integrasi & Analitik AI"><div className="flex flex-col gap-4">
        <div className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-4"><div className="flex gap-3"><ShieldCheck className="shrink-0 text-amber-300" size={18} /><div><p className="text-xs font-semibold text-amber-100">Demonstrasi tanpa pemprosesan biometrik</p><p className="mt-1 text-[10px] leading-5 text-amber-200/60">Semua pengesanan, keyakinan dan ROI ialah data sintetik. Tiada individu sebenar dikenal pasti atau dijejak.</p></div></div></div>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{aiCapabilities.map(([title, description, stat, tone]) => <article className="panel p-4" key={title}><div className="flex items-center justify-between"><span className="rounded-lg bg-cyan-500/10 p-2.5 text-cyan-300"><BrainCircuit size={18} /></span><StatusBadge tone={tone}>{tone === 'normal' ? 'Aktif' : tone === 'warning' ? 'Pantau' : 'Demo'}</StatusBadge></div><h2 className="mt-4 text-sm font-semibold text-slate-100">{title}</h2><p className="mt-2 min-h-10 text-[10px] leading-5 text-slate-500">{description}</p><div className="mt-4 flex items-center justify-between border-t border-slate-700/50 pt-3"><span className="text-[10px] font-semibold text-slate-300">{stat}</span><button aria-label={`Konfigurasi ${title}`} className="text-slate-500 hover:text-cyan-300" type="button"><Settings size={14} /></button></div></article>)}</div>
        <Panel eyebrow="Pengesanan terkini" title="Log analitik simulasi"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-[10px]"><thead className="border-b border-slate-700 text-slate-500"><tr>{['Masa', 'Keupayaan', 'Kamera', 'Lokasi', 'Keyakinan', 'Status'].map((head) => <th className="px-4 py-3" key={head}>{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-700/50">{[['06:32:18', 'Parkir Haram', 'CAM-063', 'Parkir Selatan', '96%', 'Perlu semakan'], ['06:28:44', 'Pengiraan Kenderaan', 'CAM-021', 'Jalan Tengku Kelana', '98%', 'Direkod'], ['06:21:05', 'Pagar Maya', 'CAM-014', 'Dewan Hamzah', '91%', 'Disahkan'], ['06:16:37', 'Objek Ditinggalkan', 'CAM-041', 'Pasar Jawa', '84%', 'Ditolak']].map((row) => <tr key={`${row[0]}-${row[1]}`}>{row.map((cell, index) => <td className={`px-4 py-3 ${index === 1 ? 'font-semibold text-slate-200' : 'text-slate-400'}`} key={`${row[0]}-${index}`}>{cell}</td>)}</tr>)}</tbody></table></div></Panel>
    </div></AppShell>;
}

export function ComplaintsPage() {
    return <AppShell subtitle="Sub-modul keenam yang ditunjukkan dalam wireframe Dashboard Eksekutif" title="Aduan Awam"><div className="flex flex-col gap-4">
        <div className="rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-4 text-[10px] leading-5 text-cyan-200">Skop terperinci modul Aduan belum dihuraikan dalam teks URS. Paparan ini mengikuti tab wireframe dan menggunakan metrik demonstrasi sementara untuk pengesahan MBDK.</div>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Aduan diterima', '4,826', Activity], ['Selesai dalam SLA', '85%', CheckCircle2], ['Dalam tindakan', '618', FileClock], ['Melebihi SLA', '106', BellRing]].map(([label, value, Icon], index) => <div className="panel flex items-center gap-4 p-4" key={label as string}><span className={`rounded-lg p-3 ${index === 3 ? 'bg-red-400/10 text-red-300' : 'bg-cyan-500/10 text-cyan-300'}`}><Icon size={18} /></span><span><b className="block text-xl text-white">{value as string}</b><span className="text-[10px] text-slate-500">{label as string}</span></span></div>)}</div>
        <div className="grid gap-4 xl:grid-cols-2"><Panel eyebrow="6 bulan" title="Trend penerimaan dan penyelesaian"><div className="p-2"><TrendChart /></div></Panel><Panel eyebrow="Kategori" title="Aduan mengikut zon"><div className="p-2"><ZoneBarChart /></div></Panel></div>
    </div></AppShell>;
}

export function AdminPage() {
    const [tab, setTab] = useState<'users' | 'system' | 'audit'>('system');
    return <AppShell subtitle="Pengurusan pengguna, integrasi, pelayan dan jejak audit" title="Pentadbiran Sistem"><div className="flex flex-col gap-4">
        <div className="flex flex-wrap gap-2">{[['users', 'Pengguna', Users], ['system', 'Kesihatan sistem', Server], ['audit', 'Log audit', FileClock]].map(([id, label, Icon]) => <button className={`flex items-center gap-2 rounded-lg px-3 py-2 text-[10px] font-semibold ${tab === id ? 'bg-blue-600 text-white' : 'border border-slate-700 text-slate-400'}`} key={id as string} onClick={() => setTab(id as 'users' | 'system' | 'audit')} type="button"><Icon size={13} />{label as string}</button>)}</div>
        {tab === 'users' && <UsersAdmin />}
        {tab === 'system' && <SystemAdmin />}
        {tab === 'audit' && <AuditAdmin />}
    </div></AppShell>;
}

function UsersAdmin() {
    const users = [['Ahmad Razak', 'ahmad@mbdk.gov.my', 'Jabatan IT', 'Teknologi Maklumat', 'Aktif'], ['Dato’ Ismail', 'ismail@mbdk.gov.my', 'Pengurusan Atasan', 'Pengurusan Atasan', 'Aktif'], ['Mohd Faiz', 'faiz@mbdk.gov.my', 'Penguatkuasaan', 'Pegawai Kuasa', 'Aktif'], ['Pengguna Awam', 'public@mbdk.gov.my', 'Awam', 'Awam', 'Aktif']];
    return <><div className="grid gap-3 sm:grid-cols-4">{[['Jumlah pengguna', '4'], ['Pentadbir', '1'], ['Penguat kuasa', '1'], ['Akaun beku', '0']].map(([label, value]) => <div className="panel p-4" key={label}><p className="text-[10px] text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-white">{value}</p></div>)}</div><Panel action={<button className="flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-[10px] font-semibold text-white" type="button"><Plus size={13} />Tambah pengguna</button>} eyebrow="RBAC" title="Pengurusan pengguna"><div className="border-b border-slate-700/50 p-3"><label className="flex max-w-md items-center gap-2 rounded-lg border border-slate-700 bg-slate-950/30 px-3 py-2"><Search size={13} className="text-slate-500" /><input className="flex-1 bg-transparent text-[10px] text-white outline-none" placeholder="Cari nama, e-mel atau jabatan" /></label></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-[10px]"><thead className="border-b border-slate-700 text-slate-500"><tr>{['Nama', 'E-mel', 'Jabatan', 'Peranan', 'Status', 'Tindakan'].map((head) => <th className="px-4 py-3" key={head}>{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-700/50">{users.map((row) => <tr key={row[1]}>{row.map((cell, index) => <td className={`px-4 py-3 ${index === 0 ? 'font-semibold text-slate-200' : 'text-slate-400'}`} key={`${row[1]}-${index}`}>{cell}</td>)}<td className="px-4 py-3"><button aria-label="Edit pengguna" className="text-cyan-300" type="button"><UserCog size={14} /></button></td></tr>)}</tbody></table></div></Panel></>;
}

function SystemAdmin() {
    return <><div className="grid gap-3 sm:grid-cols-3">{[['Dalam talian', '12', 'normal'], ['Terjejas', '1', 'warning'], ['Luar talian', '1', 'critical']].map(([label, value, tone]) => <div className="panel p-4" key={label}><div className="flex justify-between"><p className="text-[10px] text-slate-500">{label}</p><StatusBadge tone={tone as 'normal' | 'warning' | 'critical'}>{label}</StatusBadge></div><p className="mt-2 text-2xl font-semibold text-white">{value}</p></div>)}</div><Panel eyebrow="API & perkhidmatan" title="Kesihatan integrasi"><div className="grid gap-3 p-3 sm:grid-cols-2 xl:grid-cols-4">{integrations.map((integration) => <article className="rounded-lg border border-slate-700 bg-slate-950/30 p-4" key={integration.name}><div className="flex items-center justify-between"><Network className={integration.status === 'normal' ? 'text-emerald-400' : integration.status === 'warning' ? 'text-amber-400' : 'text-red-400'} size={16} /><StatusBadge tone={integration.status}>{integration.status}</StatusBadge></div><p className="mt-3 text-xs font-semibold text-slate-200">{integration.name}</p><p className="mt-1 text-[9px] text-slate-600">{integration.category}</p><div className="mt-3 flex justify-between border-t border-slate-700/50 pt-3 text-[9px] text-slate-500"><span>{integration.latency}</span><span>{integration.uptime}</span></div></article>)}</div></Panel><div className="grid gap-4 xl:grid-cols-2"><Panel eyebrow="Kesihatan pelayan" title="Penggunaan sumber"><div className="flex flex-col gap-5 p-4">{[['CPU', 42], ['RAM', 67], ['Storan', 53]].map(([label, value]) => <div key={label as string}><div className="flex justify-between text-[10px] text-slate-400"><span>{label as string}</span><span>{value as number}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-800"><div className={`h-2 rounded-full ${(value as number) > 60 ? 'bg-amber-400' : 'bg-blue-500'}`} style={{ width: `${value}%` }} /></div></div>)}</div></Panel><Panel eyebrow="Sandaran & pemulihan" title="Status pangkalan data"><div className="p-4"><div className="rounded-lg border border-slate-700 p-4"><p className="text-xs font-semibold text-slate-200">Sandaran terakhir</p><p className="mt-2 text-[10px] text-slate-500">25 Sep 2026, 03:00 · Berjaya</p><div className="mt-3"><StatusBadge tone="normal">Disahkan</StatusBadge></div></div><div className="mt-3 flex gap-2"><button className="flex-1 rounded-lg bg-blue-600 px-3 py-2 text-[10px] font-semibold text-white" type="button">Sandaran manual</button><button className="flex-1 rounded-lg border border-slate-700 px-3 py-2 text-[10px] font-semibold text-slate-300" type="button">Uji pemulihan</button></div></div></Panel></div></>;
}

function AuditAdmin() {
    const logs = [['06:22:00', 'Ahmad Razak', 'Log masuk', 'Auth', 'Berjaya', '10.8.1.45'], ['06:21:09', 'Mohd Faiz', 'Lihat amaran', 'ALT-001', 'Direkod', '10.8.1.47'], ['06:20:03', 'Mohd Faiz', 'Sahkan amaran', 'ALT-003', 'Berjaya', '10.8.1.47'], ['06:15:00', 'Ahmad Razak', 'Ubah konfigurasi', 'eKompaun', 'Berjaya', '10.8.1.45'], ['03:00:00', 'System', 'Sandaran', 'Database', 'Berjaya', 'localhost']];
    return <Panel action={<button className="flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-[10px] font-semibold text-slate-300" type="button"><Download size={13} />Eksport log</button>} eyebrow="Append-only" title="Log audit sistem"><div className="flex flex-wrap gap-2 border-b border-slate-700/50 p-3"><label className="flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2"><Search size={13} className="text-slate-500" /><input className="bg-transparent text-[10px] text-white outline-none" placeholder="Cari pengguna atau tindakan" /></label><button className="flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-[10px] text-slate-400" type="button"><Filter size={13} />Semua tindakan</button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-[10px]"><thead className="border-b border-slate-700 text-slate-500"><tr>{['Masa', 'Pengguna', 'Tindakan', 'Sumber', 'Hasil', 'IP'].map((head) => <th className="px-4 py-3" key={head}>{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-700/50">{logs.map((row) => <tr key={`${row[0]}-${row[1]}`}>{row.map((cell, index) => <td className={`px-4 py-3 ${index === 2 ? 'font-semibold text-cyan-300' : 'text-slate-400'}`} key={`${row[0]}-${index}`}>{cell}</td>)}</tr>)}</tbody></table></div><SourceFooter source="Jejak audit sintetik · tidak boleh dipadam" /></Panel>;
}
